name: Test

on:
  workflow_call:
    inputs:
      text:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "This is a test."
          echo "${{ inputs.text }}"
          echo "Test complete."
